import Head from 'next/head'
import '../styles/globals.scss'
import '../styles/_mixins.scss'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>jmswlkr.dev</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='preload'
          href='/fonts/MPLUSCodeLatin-Bold.ttf'
          as='font'
          crossOrigin='true'
        />
        <link
          rel='preload'
          href='/fonts/MPLUSCodeLatin-SemiBold.ttf'
          as='font'
          crossOrigin='true'
        />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='preconnect'
          href='https://fonts.googleapis.com'
        />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='true'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;700&display=swap'
          rel='stylesheet'
        ></link>
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
