import Head from 'next/head'
import { Hero } from '../components/home/01-hero'
import { ProjectList } from '../components/home/02-project-list'
import { TechStack } from '../components/home/03-tech-stack'
import { Writing } from '../components/home/04-writing'
import { Contact } from '../components/home/05-contact'
import { TopNav } from '../components/layout/top-nav'

import { layout, content, footer, social, design, linkout } from '../styles/layout/layout.module.scss'


export const getStaticProps = async () => {
  const res = await fetch(
    `http://localhost:1234/projects.json`
  )
  const data = await res.json()

  return {
    props: { projects: data },
  }
}

export default function Home({ projects }) {
  return (
    <div className={layout}>
      <Head>
        <title>jmswlkr.dev</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='preload'
          href='/fonts/MPLUSCodeLatin-Bold.ttf'
          as='font'
          crossOrigin=''
        />
        <link
          rel='preload'
          href='/fonts/MPLUSCodeLatin-SemiBold.ttf'
          as='font'
          crossOrigin=''
        />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='preconnect'
          href='https://fonts.googleapis.com'
        />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin
        />
        <link
          href='https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;700&display=swap'
          rel='stylesheet'
        ></link>
      </Head>
      <main className={content}>
        <TopNav />
        <Hero />
        <ProjectList projects={projects} />
        <TechStack />
        <Writing />
        <Contact />
      </main>
      <footer className={footer}>
        <div className={social}>
          <span>Github</span>
          <span>Codepen</span>
          <span>LinkedIn</span>
          <span>Strava</span>
        </div>
        <div className={design}>Design adapted from <span className={linkout}>Isaac Fayemi</span></div>
      </footer>
    </div>
  )
}
